---
- hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: Install docker system dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
    - name: Make sure docker is started
      service:
        name: docker
        state: started
        enabled: yes
    - name: Add "{{ansible_user}}" user to "docker" group
      user:
        name: "{{ansible_user}}"
        groups: "docker"
        append: yes
    - name: Create a data container
      docker_container:
        name: nginx-test
        image: nginx:latest
        pull: true
        ports:
          - "80:80"
        state: started
  handlers:
    - name: Restart docker
      service: 
        name: docker 
        state: restarted